### ISSUE TITLE
RMB Stopped Working in Chrome 60 (Beta)

### ISSUE THREAD

**Issue by pureby** [davidparsson/scrollbar-anywhere#57] opened 2017-06-17 09:32 UTC
RMB stopped working since Chrome v60 update. It simply does not trigger any action — not on webpages, not even in ScrollbarAnywhere's own settings page :-(

I have tried enabling (and disabling) the trigger-keys (Ctrl/Alt/Shift) in settings, but it does not help.

MMB doesn't work either. LMB still works, but obviously, it's not a usable alternative.

My setup:
- Mouse button used when scrolling: RMB (right)
- Chrome version: 60.0.3112.32 (Official Build) beta (64-bit)
- Operating system: Windows 10 64-bit

**Comment by davidparsson** [comment] 2017-07-22 15:54
Thanks for reporting! I've found the cause and fixed it in `v2.12`, which is being uploaded at this very moment.

**Comment by pureby** [comment] 2017-07-23 22:27
The last month reminded me how browsing was like before you created this awesome little extension.
Thanks for fixing, @davidparsson ! Now I can finally browse happily again :-D

**Comment by davidparsson** [comment] 2017-07-26 07:55
My pleasure! And thanks for showing your appreciation! People not taking things for granted makes this open-source thing much more enjoyable. 😊

**Comment by Andreasvb** [comment] 2017-07-30 10:27
I guess it's back in 61, no buttons work. =/

Version 61.0.3163.14 (Official Build) dev (64-bit)
![image](https://user-images.githubusercontent.com/3948747/28752529-74d76000-7522-11e7-964c-899dd359ea81.png)

**Comment by davidparsson** [comment] 2017-08-02 20:55
All right, I'll take a new look when I'm back home again.

**Comment by davidparsson** [comment] 2017-08-04 10:16
@Andreasvb, those issues are hopefully fixed by #58 and #59. I'll release 2.13 shortly with fixes for these issues.

**Closed by davidparsson** 2017-08-04 10:16 UTC

**Comment by davidparsson** [comment] 2017-08-04 11:10
@Andreasvb, 2.13 is released. Please let me know if it fixes your issues.

**Comment by Andreasvb** [comment] 2017-08-04 11:42
Works fine now.
Version 61.0.3163.26 (Official Build) dev (64-bit)

**Comment by vsemozhetbyt** [comment] 2017-08-04 13:29
Thank you! Works fine in the Chrome Canary 62.
