### ISSUE TITLE
doesn't work when opening local html file

### ISSUE THREAD

**Issue by whimian** [davidparsson/scrollbar-anywhere#71] opened 2018-06-12 03:12 UTC
When open local html file, it just won't work.

My setup:
- Mouse button used when scrolling: Right
- Chrome version: 66.0.3359.117
- Operating system: Windows 10

**Comment by vsemozhetbyt** [comment] 2018-06-12 04:31
Did you toggle "Allow access to file URLs" on in the extension settings?

**Comment by whimian** [comment] 2018-06-12 04:37
@vsemozhetbyt   Yes, I did.
![tim 20180612123503](https://user-images.githubusercontent.com/3821278/41270340-3475c2c6-6e3d-11e8-87fa-98c3ce6882d3.png)

**Comment by davidparsson** [comment] 2018-06-12 05:36
Hi @whimian, and thanks for reporting. I can reproduce this. There seems to be an issue with the domain blacklisting, causing the emtpy host used for local files to be matched against an empty blacklist.

**Comment by davidparsson** [comment] 2018-06-12 05:57
Fixed in `2.15` which is being made available to users at this moment.

**Closed by davidparsson** 2018-06-12 05:57 UTC
Labels: Bug

**Comment by whimian** [comment] 2018-06-13 00:39
@davidparsson Works like a charm now. Thank you so much.
